language: php
dist: trusty

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
  
env:
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*
  - SYMFONY_VERSION=3.2.*
  - SYMFONY_VERSION=3.3.*
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.0.*
  - SYMFONY_VERSION=4.1.*
  - DEPENDENCIES="beta"
  
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=4.0.*
    - php: 5.6
      env: SYMFONY_VERSION=4.1.*
    - php: 7.0
      env: SYMFONY_VERSION=4.0.*
    - php: 7.0
      env: SYMFONY_VERSION=4.1.*
  allow_failures:
    - php: hhvm
    - php: nightly

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update --prefer-dist

script:
  - vendor/bin/phpunit
